# Generated by Django 4.1.2 on 2022-11-01 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_auto_20221029_0106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_albums", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
